### ISSUE TITLE
Can you explain it for me about ……

### ISSUE THREAD

**Issue by lixunlove** [cyberport-kaggle/galaxy-zoo#1] opened 2015-03-16 08:11 UTC
@hxu 

Thanks for sharing your project code.
I am a beginner learning machine,I do not know about “ Use the 12,000 features (3,000 centroids x 4 quadrants) to train a ridge regressor on all 37 response columns”Can you explain it for me？

Thanks

**Comment by hxu** [comment] 2015-03-22 22:13
You're going to have to elaborate a bit more about what part you don't understand, as there is quite a bit in here.  But the general idea is that you generate 12,000 features from the pipeline, which is described in greater detail in the paper we reference.  Then you use those features in a ridge regression model, of the form

```
y1 =  x1 + x2 + x3 ... x12000
y2 =  x1 + x2 + x3 ... x12000
....
y37 = x1 + x2 + x3 ... x12000
```

(coefficients and error terms excluded)

**Comment by lixunlove** [comment] 2015-03-23 08:08
Thank you for your reply, after carefully reading the references I understood how it works, and I only 8-core computer with 16G  RAM, there is no enough RAM to run the program（I tried to run the program）, can send your pkl files sent to me ? My Email address lixunlove@gmail.com ,Thank you.

**Comment by hxu** [comment] 2015-03-23 09:34
Sorry, it's been some time since I've run this code and have since discarded all files.  It should be no problem for 16GB, though, so not sure why you're encountering issues.  You may consider using a cloud instance on AWS or from Aliyun for more RAM.

Closing this ticket.

**Closed as completed by hxu** 2015-03-23 09:34 UTC
